### ISSUE TITLE
Add support for Alfred 3

### ISSUE THREAD

**Issue by peschee** [josefweibel/Public-Transport-Timetable-Alfred-Workflow#8]
The workflow does not work for Alfred 3. It cannot create the cache directory because of this line

https://github.com/josefweibel/Public-Transport-Timetable-Alfred-Workflow/blob/96343ab5a600928573b1aae1c0b59862fbd96bfc/src/Utils/WorkflowUtil.php#L139

What you probably could use / add, is the `alfred_workflow_cache` env var documented here https://www.alfredapp.com/help/workflows/script-environment-variables/

**Comment by josefweibel** [comment]
Thank you for reporting this bug. It has been resolved and a new version of the workflow is available at https://www.josefweibel.ch/alfred/fahrplan/.
